//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSSBuilder.MessageStrings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSSBuilderStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSSBuilderStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSSBuilder.MessageStrings.RSSBuilderStrings", typeof(RSSBuilderStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feed was published before to a different FTP site. Are you sure you want to publish to the selected FTP site?.
        /// </summary>
        internal static string msgAskChangeSite {
            get {
                return ResourceManager.GetString("msgAskChangeSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected topic?.
        /// </summary>
        internal static string msgAskDelete {
            get {
                return ResourceManager.GetString("msgAskDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save to this location.
        /// </summary>
        internal static string msgCannotSave {
            get {
                return ResourceManager.GetString("msgCannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed has changed. Do you want to save the changes?.
        /// </summary>
        internal static string msgChanged {
            get {
                return ResourceManager.GetString("msgChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first time this feed is being published. The feed will be linked to the selected FTP site. Are you sure you want to publish to the selected site?&quot;.
        /// </summary>
        internal static string msgFirstPublish {
            get {
                return ResourceManager.GetString("msgFirstPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file does not contain a valid RSS feed.
        /// </summary>
        internal static string msgInvalidRSS {
            get {
                return ResourceManager.GetString("msgInvalidRSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected language will become effective after restarting RSS Builder.
        /// </summary>
        internal static string msgLanguage {
            get {
                return ResourceManager.GetString("msgLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Text.
        /// </summary>
        internal static string strTest {
            get {
                return ResourceManager.GetString("strTest", resourceCulture);
            }
        }
    }
}
